'use client';
import {useEffect, useState} from 'react';

type Prize = {id: string; label: string; coinAmount: number; weight: number; active: boolean; sortOrder: number};
type Spin = {id: string; customer: {name: string; email: string}; order: {code: string}; prizeLabel: string | null; coinAmount: number | null; spunAt: string | null; createdAt: string};
const initialPrize = (): Prize => ({id: '', label: '', coinAmount: 5_000_000, weight: 1, active: true, sortOrder: 0});
const number = (value: number) => value.toLocaleString('en-US');

export default function LuckyWheelAdmin() {
  const [prizes, setPrizes] = useState<Prize[]>([]); const [history, setHistory] = useState<Spin[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function load() { const response = await fetch('/api/admin/lucky-wheel', {cache: 'no-store'}); const body = await response.json(); if (!response.ok) throw new Error(body.error); setPrizes(body.prizes); setHistory(body.history); }
  useEffect(() => { void load().catch(cause => setError(cause instanceof Error ? cause.message : 'Could not load lucky wheel.')); }, []);
  function update(index: number, patch: Partial<Prize>) { setPrizes(current => current.map((item, i) => i === index ? {...item, ...patch} : item)); }
  async function save() { setBusy(true); setError(''); setMessage(''); const response = await fetch('/api/admin/lucky-wheel', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({prizes})}); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) {setError(body.error ?? 'Could not save prizes.'); return;} setPrizes(body.prizes); setMessage('Lucky wheel settings saved.'); }
  return <div className="lucky-admin-grid"><section className="card admin-panel"><div className="admin-panel-heading"><div><h2>Prize configuration</h2><p className="muted">Weights are relative. For example, weight 40 is four times more likely than weight 10.</p></div><button type="button" onClick={() => setPrizes(current => [...current, {...initialPrize(), sortOrder: current.length}])}>Add prize</button></div>{prizes.map((item, index) => <div className="lucky-prize-row" key={item.id || `new-${index}`}><label>Label<input value={item.label} onChange={event => update(index, {label: event.target.value})} placeholder="5M coins"/></label><label>Coins<input type="number" min="1" value={item.coinAmount} onChange={event => update(index, {coinAmount: Math.floor(Number(event.target.value))})}/></label><label>Weight<input type="number" min="0" value={item.weight} onChange={event => update(index, {weight: Math.floor(Number(event.target.value))})}/></label><label className="admin-compact-check"><input type="checkbox" checked={item.active} onChange={event => update(index, {active: event.target.checked})}/> Active</label><button type="button" className="secondary" onClick={() => setPrizes(current => current.filter((_, i) => i !== index))}>Remove</button></div>)}<div className="admin-form-actions"><button type="button" disabled={busy} onClick={() => void save()}>{busy ? 'Saving…' : 'Save prizes'}</button>{message && <span className="admin-feedback success">{message}</span>}{error && <span className="admin-feedback error">{error}</span>}</div></section><section className="card admin-panel"><h2>Spin history</h2><p className="muted">Latest 200 issued spins. Unused spins show as pending.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Order</th><th>Prize</th><th>Issued</th><th>Spun</th></tr></thead><tbody>{history.length ? history.map(item => <tr key={item.id}><td><strong>{item.customer.name}</strong><span>{item.customer.email}</span></td><td>{item.order.code}</td><td>{item.prizeLabel ?? 'Pending'}</td><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.spunAt ? new Date(item.spunAt).toLocaleString() : 'Not used'}</td></tr>) : <tr><td colSpan={5} className="admin-empty">No spins yet.</td></tr>}</tbody></table></div></section></div>;
}
