'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useLocale, useTranslations} from 'next-intl';
import {useEffect, useState} from 'react';
import {products, Locale, usd} from '@/lib/catalog';
import {useCart} from './cart-provider';

export function ProductArt({variant = 0}: {variant?: number}) {
  return <div className={`product-art art-${variant}`} aria-hidden="true"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><div className="isometric"><i/><i/><i/></div><span className="art-caption">DIGITAL / {variant ? 'PLUS' : 'ESSENTIAL'}</span><span className="art-number">0{variant + 1}</span></div>;
}
export function StoreHeader() {
  const locale = useLocale(); const vi = locale === 'vi'; const path = usePathname(); const {lines} = useCart(); const [account, setAccount] = useState<{name: string; role: string} | null>(null);
  useEffect(() => {fetch('/api/auth/session').then(r => r.json()).then(data => setAccount(data.account)).catch(() => undefined);}, [path]);
  async function logout() {await fetch('/api/auth/logout', {method: 'POST'}); setAccount(null); window.location.reload();}
  return <header className="site-header"><div className="shell header"><Link href={`/${locale}`} className="brand"><span className="brand-symbol">S↗</span><span>SHOP<small>CONCEPT / 01</small></span></Link><nav aria-label={vi ? 'Điều hướng' : 'Navigation'}><Link href={`/${locale}#catalog`}>{vi ? 'Khám phá' : 'Explore'}</Link><Link href={`/${locale}#how-it-works`}>{vi ? 'Cách mua' : 'How it works'}</Link><Link href={`/${locale}/workspace`}>{vi ? 'Tư vấn' : 'Chat support'}</Link><Link href={`/${locale}#faq`}>{vi ? 'Trợ giúp' : 'Help'}</Link></nav><div className="header-actions"><div className="language-switch"><Link aria-current={vi ? 'page' : undefined} href={path.replace(/^\/(vi|en)/, '/vi')} lang="vi">VI</Link><Link aria-current={!vi ? 'page' : undefined} href={path.replace(/^\/(vi|en)/, '/en')} lang="en">EN</Link></div>{account ? <span className="account-menu"><Link href={`/${locale}/workspace`}>{account.name}</Link><button className="secondary" onClick={() => void logout()}>{vi ? 'Đăng xuất' : 'Log out'}</button></span> : <Link className="text-link" href={`/${locale}/login`}>{vi ? 'Đăng nhập / Đăng ký' : 'Sign in / Register'}</Link>}<Link className="cart-link" aria-label={vi ? 'Giỏ hàng' : 'Cart'} href={`/${locale}/cart`}>{vi ? 'Giỏ hàng' : 'Cart'} <b>{lines.reduce((sum,l) => sum+l.quantity,0)}</b></Link></div></div></header>;
}
export function Catalog() {
  const locale = useLocale() as Locale; const vi = locale === 'vi'; const t = useTranslations();
  const [query,setQuery] = useState(''); const [filter,setFilter] = useState('all'); const [sort,setSort] = useState('asc');
  const visible = products.filter(p => p.title[locale].toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (filter === 'all' || p.id === filter)).sort((a,b) => sort === 'asc' ? a.usdCents-b.usdCents : b.usdCents-a.usdCents);
  return <section id="catalog" className="section"><div className="section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>{vi ? 'Tìm gói phù hợp với bạn' : 'Find your next digital pick'}</h2><p className="muted">{vi ? 'Hai gói mẫu để khám phá trải nghiệm mua sắm.' : 'Two sample packages to explore the shopping experience.'}</p></div><span className="pill">USD · {vi ? 'Giá minh họa' : 'Demo prices'}</span></div><div className="catalog-tools"><label className="search-field"><span>⌕</span><input aria-label={vi ? 'Tìm sản phẩm' : 'Search products'} placeholder={vi ? 'Tìm sản phẩm, gói dịch vụ...' : 'Search products, packages...'} value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label={vi ? 'Sắp xếp' : 'Sort'} value={sort} onChange={e => setSort(e.target.value)}><option value="asc">{vi ? 'Giá: thấp đến cao' : 'Price: low to high'}</option><option value="desc">{vi ? 'Giá: cao đến thấp' : 'Price: high to low'}</option></select></div><div className="filter-row">{[['all',vi ? 'Tất cả' : 'All packages'],['sample-basic','Essential'],['sample-plus','Plus']].map(([value,label]) => <button className={`filter-chip ${filter === value ? 'active' : ''}`} aria-pressed={filter === value} key={value} onClick={() => setFilter(value)}>{label}</button>)}<span className="muted" aria-live="polite">{visible.length} {vi ? 'kết quả' : 'results'}</span></div><div className="product-grid">{visible.map(p => <article className="product-card" key={p.id}><ProductArt variant={p.id === 'sample-basic' ? 0 : 1}/><div className="product-content"><div className="row"><span className="eyebrow">DIGITAL PACKAGE</span><span className="sample-tag">DEMO</span></div><h3>{p.title[locale]}</h3><p className="muted">{p.description[locale]}</p><div className="product-bottom"><div><small>{vi ? 'Giá gói mẫu' : 'Sample price'}</small><p className="price">{usd(p.usdCents,locale)}</p></div><Link className="button secondary" href={`/${locale}/products/${p.id}`}>{t('detail')} <span aria-hidden="true">↗</span></Link></div></div></article>)}</div>{!visible.length && <div className="empty-state"><h3>{vi ? 'Không tìm thấy gói phù hợp' : 'No matching packages'}</h3><button onClick={() => {setQuery('');setFilter('all');}}>{vi ? 'Xóa bộ lọc' : 'Reset filters'}</button></div>}</section>;
}