'use client';
import {useEffect, useState} from 'react';

type Product = {id: string; slug: string; active: boolean; category: string; sortOrder: number; imagePath: string; translations: Record<string, {title: string; description: string}>; packages: any[]};
const emptyPackage = () => ({sku: '', baseUsdCents: 100, saleUsdCents: null, stockOnHand: 0, active: false, translations: {en: {title: '', description: ''}}, fields: [{key: 'recipient', labelEn: 'Recipient', required: true, maxLength: 80}]});
const empty = (): Product => ({id: '', slug: '', active: false, category: 'general', sortOrder: 0, imagePath: '', translations: {en: {title: '', description: ''}}, packages: [emptyPackage()]});
// Older records may still carry Vietnamese labels; drop them so the English-only schema accepts the save.
const englishFields = (fields: any[] = []) => fields.map(({key, labelEn, required, maxLength}) => ({key, labelEn, required, maxLength}));

export default function ProductsAdmin() {
  const [products, setProducts] = useState<Product[]>([]); const [current, setCurrent] = useState(empty()); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); try { const r = await fetch('/api/admin/products'); const d = await r.json(); if (!r.ok) throw new Error(d.error); setProducts(d.products); } catch (e) { setError(e instanceof Error ? e.message : 'Load failed'); } finally {setBusy(false);} }
  useEffect(() => {void load();}, []);
  function update(path: string, value: unknown) { setCurrent(prev => {const next = structuredClone(prev) as Product; const parts = path.split('.'); let target: any = next; parts.slice(0, -1).forEach(p => {target = target[p];}); target[parts.at(-1)!] = value; return next;}); }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try {const payload = {id: current.id || undefined, slug: current.slug, category: current.category, sortOrder: current.sortOrder, imagePath: current.imagePath, active: current.active, en: current.translations.en, packages: current.packages.map(p => ({sku:p.sku, baseUsdCents:p.baseUsdCents, saleUsdCents:p.saleUsdCents, stockOnHand:p.stockOnHand, active:p.active, en:p.translations.en, fields:englishFields(p.fields)}))}; const r=await fetch('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const d=await r.json(); if(!r.ok) throw new Error(d.error); setMessage('Product saved'); await load(); setCurrent(empty());} catch(e){setError(e instanceof Error?e.message:'Save failed');} finally{setBusy(false);} }
  async function remove(id: string) {if(!window.confirm('Delete this product?'))return; const r=await fetch(`/api/admin/products?id=${id}`,{method:'DELETE'}); if(r.ok) await load(); else {const d=await r.json();setError(d.error);}}
  const shown=products.filter(p=>`${p.slug} ${p.translations.en?.title}`.toLowerCase().includes(query.toLowerCase()));
  return <div><div className="page-heading"><p className="eyebrow">ADMIN / SETTINGS / PRODUCTS</p><h1>{'Products'}</h1><p className="notice">{'Manage products, packages, sale prices, stock and delivery forms. PostgreSQL is required to persist data.'}</p></div><section className="card"><input placeholder={'Search name or slug'} value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>setCurrent(empty())}>{'Add product'}</button>{shown.map(p=><p key={p.id}><button onClick={()=>setCurrent(p)}>{p.translations['en']?.title||p.slug}</button> · {p.slug} · {p.active?'ON':'OFF'} · <button onClick={()=>void remove(p.id)}>{'Delete'}</button></p>)}</section><form className="card" onSubmit={save}><h2>{current.id? 'Edit product' : 'New product'}</h2><label>Slug<input required value={current.slug} onChange={e=>update('slug',e.target.value)}/></label><label>{'Title'}<input required value={current.translations.en?.title ?? ''} onChange={e=>update('translations.en.title',e.target.value)}/></label><label>{'Description'}<textarea value={current.translations.en?.description ?? ''} onChange={e=>update('translations.en.description',e.target.value)}/></label><label>Category<input value={current.category} onChange={e=>update('category',e.target.value)}/></label><label><input type="checkbox" checked={current.active} onChange={e=>update('active',e.target.checked)}/> {'Active'}</label><h3>{'Packages / variants'}</h3>{current.packages.map((p,i)=><div key={i}><label>SKU<input required value={p.sku} onChange={e=>update(`packages.${i}.sku`,e.target.value)}/></label><label>{'Package name'}<input required value={p.translations.en?.title ?? ''} onChange={e=>update(`packages.${i}.translations.en.title`,e.target.value)}/></label><label>{'Base price (USD cents)'}<input type="number" min="1" value={p.baseUsdCents} onChange={e=>update(`packages.${i}.baseUsdCents`,Number(e.target.value))}/></label><label>{'Sale price (blank for none)'}<input type="number" min="1" value={p.saleUsdCents??''} onChange={e=>update(`packages.${i}.saleUsdCents`,e.target.value?Number(e.target.value):null)}/></label><label>{'Stock'}<input type="number" min="0" value={p.stockOnHand} onChange={e=>update(`packages.${i}.stockOnHand`,Number(e.target.value))}/></label><label><input type="checkbox" checked={p.active} onChange={e=>update(`packages.${i}.active`,e.target.checked)}/> {'Package active'}</label></div>)}<button type="button" onClick={()=>setCurrent(prev=>({...prev,packages:[...prev.packages,emptyPackage()]}))}>{'Add package'}</button> <button disabled={busy} type="submit">{busy? 'Saving...' : 'Save product'}</button><p role="alert">{error}</p><p role="status">{message}</p></form></div>;
}