import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Catalog, ProductArt} from '@/components/store-ui';

export default async function Store({params}: {params: Promise<{locale: string}>}) {
  const {locale} = await params;
  if (locale !== 'vi' && locale !== 'en') notFound();
  const vi = locale === 'vi';
  return <>
    <div className="floating-horse-1" aria-hidden="true"></div>
    <div className="floating-horse-2" aria-hidden="true"></div>
    <section className="hero"><div className="hero-copy"><span className="pill">✦ {vi ? 'Không gian mua sắm số · UI preview' : 'Your digital storefront · UI preview'}</span><h1>{vi ? <>Sản phẩm số.<br/>Trải nghiệm <em>khác biệt.</em></> : <>Digital goods.<br/>A better <em>experience.</em></>}</h1><p>{vi ? 'Từ lựa chọn đầu tiên đến bước đặt hàng cuối cùng. Khám phá một trải nghiệm mua sắm rõ ràng, gọn gàng và dành cho bạn.' : 'From your first discovery to the final checkout. Explore a clear, considered shopping experience built around you.'}</p><div className="hero-actions"><Link className="button" href="#catalog">{vi ? 'Khám phá các gói' : 'Explore packages'} →</Link><Link className="text-link" href="#how-it-works">{vi ? 'Cách mua hàng' : 'How it works'} ↗</Link></div><div className="hero-meta"><span>VI / EN</span><span>USD · {vi ? 'Giá mẫu' : 'Sample prices'}</span><span>{vi ? 'Giao thủ công' : 'Manual fulfillment'}</span></div></div><div className="hero-visual"><div className="visual-label">A NEW WAY TO EXPLORE <span>↗</span></div><ProductArt/><div className="floating-card"><span>✦</span><div><strong>{vi ? 'Từng chi tiết, rõ ràng.' : 'Every detail, considered.'}</strong><small>{vi ? 'Chọn gói → Giỏ hàng → Checkout' : 'Discover → Cart → Checkout'}</small></div></div><div className="visual-bottom">COLLECTION 01 <span>INTERACTIVE CONCEPT</span></div></div></section>
    <div className="feature-strip">{(vi ? [['01','Song ngữ','Tiếng Việt & English'],['02','Thông tin minh bạch','Xem giá và chi tiết trước khi mua'],['03','Theo từng gói','Biểu mẫu giao hàng riêng']] : [['01','Two languages','Vietnamese & English'],['02','Clear information','Review prices and details first'],['03','Package by package','Individual delivery forms']]).map(([n,title,desc]) => <div key={n}><span className="feature-index">{n}</span><div><strong>{title}</strong><small>{desc}</small></div></div>)}</div>
    <Catalog/>
    <section id="how-it-works" className="section how-section"><p className="eyebrow">HOW IT WORKS</p><h2>{vi ? 'Đơn giản từ đầu đến cuối.' : 'Simple, from start to finish.'}</h2><div className="steps-grid">{(vi ? [['Chọn gói của bạn','Khám phá danh mục và xem thông tin gói.'],['Điền thông tin','Mỗi gói có biểu mẫu riêng. Chỉ dùng dữ liệu thử.'],['Thử checkout','Xem lại đơn và thử thanh toán mô phỏng.']] : [['Find your package','Browse the collection and review package details.'],['Add your details','Each package has its own form. Use test data only.'],['Explore checkout','Review your order and try a simulated payment.']]).map(([title,desc],i) => <article key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p className="muted">{desc}</p></article>)}</div></section>
    <section id="faq" className="section faq-section"><div><p className="eyebrow">GOOD TO KNOW</p><h2>{vi ? 'Trước khi bạn bắt đầu.' : 'Before you get started.'}</h2></div><div>{(vi ? [['Có thể mua hàng thật chưa?','Chưa. Prototype không thu tiền, không tạo đơn thật và không giao sản phẩm.'],['Có hỗ trợ VND và EUR không?','Bản demo chỉ dùng USD. Nguồn tỷ giá và thanh toán vẫn cần xác minh.'],['Liên hệ hỗ trợ như thế nào?','Dự kiến qua Discord/email. Kênh chính thức chưa được cấu hình; bản demo không sử dụng thông tin liên hệ giả.']] : [['Can I make a real purchase?','Not yet. This prototype does not collect payments, create real orders or deliver products.'],['Can I use VND or EUR?','This demo uses USD only. Exchange rates and payment availability still need verification.'],['How can I contact support?','Discord/email are planned. Official channels are not configured; no invented contact details are displayed.']]).map(([q,a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
  </>;
}